name: ROS2 CI

on:
  issue_comment:
    types:
    - created
  merge_group:
    types: [checks_requested]
    branches: [develop]

defaults:
  run:
    working-directory: ./raspberryPI3/ros2_ws

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-ros')

    steps:
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v1
      id: comment-branch

    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.comment-branch.outputs.head_ref }}

    - name: Set up ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        ros-distro: humble
        install-ros-dependencies: true

    - name: Get ROS 2 dependencies
      run: |
        sudo apt update
        sudo apt install ros-humble-rviz2 -y

    - name: Build with colcon
      run: |
        colcon build --packages-select interfaces
        colcon build --packages-skip interfaces rviz_imu_plugin

    - name: Set latest commit status as ${{ job.status }}
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}

    - name: Add comment to PR
      uses: actions/github-script@v6
      if: always()
      with:
        script: |
          const name = '${{ github.workflow   }}';
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const success = '${{ job.status }}' === 'success';
          const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })